name: Release

on:
  push:
    # tags:
    #   - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: corepack pnpm install --frozen-lockfile
      - name: Lint
        run: corepack pnpm run lint
      - name: Build
        run: corepack pnpm run build:prod
      - uses: actions/upload-artifact@v4
        with:
          name: export-attendance-csv.user.js
          path: dist/export-attendance-csv.user.js
