name: Build & Release

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ startsWith(github.ref, 'refs/tags/') && 'production' || 'development' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: corepack pnpm install --frozen-lockfile
      - name: Lint
        run: corepack pnpm run lint
      - name: Build
        run: corepack pnpm run build:prod
      - uses: actions/upload-artifact@v4
        with:
          name: export-attendance-csv.user.js
          path: dist/export-attendance-csv.user.js
  release:
    name: Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: export-attendance-csv.user.js
      - uses: softprops/action-gh-release@v2
        with:
          files: export-attendance-csv.user.js
